#!/usr/bin/env bash
JOB_NAME=$1
App_Type=$2
Suffix_Code=None  # 查找确定路径下有没有应用所选择的包
File_TMP_WAR=/tmp/${JOB_NAME}/File_TMP_WAR
File_TMP_JAR=/tmp/${JOB_NAME}/File_TMP_JAR
Target_JAR_Path=None  # 获取打包完成之后JAR/WAR包完整路径名称名称
TMP_FileSize=None
JAR_WAR_NAME=None       # 定义SpringBoot Jar包名称，用来获取打包之后的名称
JAR_WAR_SIZE=None
BUILD_ENV=$3
Kubernetes_Deployment_Service=$4  # 定义K8S中Metadata name名称
Kubernetes_Deployment_File_DIR=/usr/local/jenkins/kubernetes/deployment/  # 定义deployment文件存放的目录
Deployment_File_Name=$5  # 定义Deployment文件名称
Service_File_Name=$6     # 定义Service文件名称
#WAR_NAME=None       # 定义Tomcat war包名称，用来获取打包之后的名称
#JAR_SIZE=None       # 获取JAR包文件大小
#WAR_SIZE=None       # WAR包文件大小
Link_Base_Dir=None
TIME_VERSION=None
DEST_Package_Name=None #定义生成包名称
Front_Base_Dir=/usr/local/jenkins/workspace/${JOB_NAME}/  # 定义前端构建位置目录
Pack_Base_Dir=/usr/local/jenkins/package/${JOB_NAME}  # 定义存放包目录
# 定义workspace
Target_Path=/usr/local/jenkins/workspace/${JOB_NAME}/target/
# 定义镜像文件构建时的目录
# 定义后端镜像构建目录
IMAGE_BUILD_SERVER_DIR=/usr/local/jenkins/build-server/${JOB_NAME}
# 定义前端镜像构建目录
IMAGE_BUILD_FRONT_DIR=/usr/local/jenkins/build-front/${JOB_NAME}

# 判断临时文件目录是否存在
if [[ ! -d /tmp/${JOB_NAME} ]] ;then
         mkdir  -p /tmp/${JOB_NAME}
fi
# 判断存放包目录是否存在
if [[ ! -d ${Pack_Base_Dir} ]] ;then
         mkdir  -p $Pack_Base_Dir
         echo "存放包目录创建成功: $Pack_Base_Dir"
fi
# 判断应用的类型
function Get_App_Type(){
    if [[ "${App_Type}" == "SpringBoot" ]] ;then
        App_Type="SpringBoot"
        echo "App类型为:${App_Type}"
    elif [[ "${App_Type}" == "Tomcat" ]] ; then
         App_Type="Tomcat"
        echo "App类型为${App_Type}"
    elif [[ "${App_Type}" == "Static" ]] ; then
         App_Type="Static"
        echo "App类型为前端静态文件${App_Type}"
    else
        echo "App类型选择错误"
     exit 2
    fi
}
# 获取生产包路径及包名称和大小
function Get_File_Name_Size() {
    JAR_WAR_NAME=`ls -l ${Target_JAR_Path} | awk -F \/ '{print$NF}'`
    JAR_WAR_SIZE=`du -sh ${Target_JAR_Path} | awk '{print$1}'`
    echo "${App_Type}构建生成的包完整路径为: $Target_JAR_Path"
    echo "${App_Type}构建生成的包为:$JAR_WAR_NAME "
    echo "${App_Type}构建生成的包大小为:$JAR_WAR_SIZE "
    echo "开始删除本次构建生成的临时文件"
}
# 复制包到目标目录及获取目标完整路径
function Get_File_Absolute () {
        # 定义源路径
        Source_Full_Path=$Target_Path$JAR_WAR_NAME
        # 定义保存到Package目录下的包名称
        Target_Dest_Name=`date +%F-%R`-$JAR_WAR_NAME
        echo "Target_Dest_Name=$Target_Dest_Name"
        echo "源路径$Source_Full_Path"
        # 定义复制到目标目录完整路径
        Target_Dest_Full_Path=$Pack_Base_Dir/$Target_Dest_Name
        cp $Source_Full_Path  $Target_Dest_Full_Path
        echo "定义复制到目标目录完整路径: $Target_Dest_Full_Path"
        [ $? -eq 0 ] && echo "文件复制成功"
}
function Find_File_Suffix(){
       if [[ "${App_Type}" == "Tomcat" ]] ; then
            echo "##############Tomcat###############"
            # 将查找文件的结果输出到临时文件并判断临时文件的大小
            Target_Path=${Target_Path}
            find ${Target_Path} -name "*.war" > ${File_TMP_WAR}
            # # 通过查找文件大小来判断，文件后缀名是否存在
            FileSize=`ls -l "${File_TMP_WAR}" | awk '{print$5}'`
            echo "$File_TMP_WAR文件大小为: $TMP_FileSize"
            if [[ "${FileSize}" -eq 0 ]] ; then
                    echo "Tomcat War包判断不存在"
                    echo "开始删除$File_TMP_WAR"
                    rm -rf $File_TMP_WAR && [ $? -eq 0 ] &&   "临时文件$File_TMP_WAR删除成功"
                    echo "应用类型选择错误"
            else
                    find $Target_Path -name "*.war" > "$File_TMP_WAR"
                    Target_JAR_Path=`cat $File_TMP_WAR`
#                    JAR_WAR_NAME=`ls -l ${Target_JAR_Path} | awk -F \/ '{print$NF}'`
#                    JAR_WAR_SIZE=`du -sh ${Target_JAR_Path} | awk '{print$1}'`
#                    echo "${App_Type}构建生成的包完整路径为: $Target_JAR_Path"
#                    echo "${App_Type}构建生成的包为:$JAR_WAR_NAME "
#                    echo "${App_Type}构建生成的包大小为:$JAR_WAR_SIZE "
#                    echo "开始删除本次构建生成的临时文件"
                    Get_File_Name_Size  # 调用函数
                    rm -rf $File_TMP_WAR && [ $? -eq 0 ] && echo "临时文件$File_TMP_WAR删除成功"
            fi
       elif [[ "${App_Type}" == "Static" ]] ; then
             echo "#############静态文件####################"
             echo "对静态文件进行打包处理"
             # cd $Pack_Base_Dir
             # Exist_Dist_Dir 删除存在的目录
             Exist_Dist_Dir=${Pack_Base_Dir}/dist
             # echo "$Exist_Dist_Dir"
             if [[ ! -d "${Exist_Dist_Dir}" ]] ;then
                  rm -rf ${Exist_Dist_Dir}
                  echo "原始打包文件删除"
              fi
             echo "开始执行打包命令，请耐心等待...."
             source /etc/profile.d/nodejs.sh
             npm install && npm run build--$BUILD_ENV
             if [ $? -eq 0 ] ;then
                  echo "静态资源文件打包成功"
                  echo "开始对静态文件进行打包操作"
                  # New_Packge_Name 定义打包生成的压缩文件名称
                  New_Packge_Name=`date +%F-%R`-${JOB_NAME}-${BUILD_ENV}-dist.zip
                  # Front_Base_Dir 定义源构建生成的文件的完整路径
                  # Front_Base_Dir=/usr/local/jenkins/workspace/${JOB_NAME}/dist
                  # 打包之后存放的文件目录
                  cd ${Front_Base_Dir}
                  echo "当前目录为:$Front_Base_Dir"
                  Front_Target_Dir=/usr/local/jenkins/front-packages/
                  zip -r ${New_Packge_Name}  dist &> /dev/null
                  [ $? -eq 0 ] && mv ${New_Packge_Name} ${Front_Target_Dir}
                  [ $? -eq 0 ] && echo "打包操作成功"
                  # Front_Target_Full_Path 定义打包生成后的完整路径
                  Front_Target_Full_Path=${Front_Target_Dir}${New_Packge_Name}
                  echo "打包生成的完整路径为: ${Front_Target_Full_Path}"
                  # 动态创建构建目录
#                  if [[ ! -d ${IMAGE_BUILD_FRONT_DIR} ]] ; then
#                            mkdir -p ${IMAGE_BUILD_FRONT_DIR}
#                            echo "构建目录已生成:${IMAGE_BUILD_FRONT_DIR}"
#                  fi
                  \cp -f ${Front_Target_Full_Path}  /usr/local/jenkins/build_rms_front/dist.zip
                  [ $? -eq 0 ] && echo "文件已经复制到Docker构建镜像目录"
             else
                   echo "静态资源文件打包失败"
             fi
       else
        echo "##############SpringBoot###############"
        find $Target_Path -name "*.jar" > "$File_TMP_JAR"
        Target_JAR_Path=`cat $File_TMP_JAR`
#        JAR_WAR_NAME=`ls -l ${Target_JAR_Path} | awk -F \/ '{print$NF}'`
#        JAR_WAR_SIZE=`du -sh ${Target_JAR_Path} | awk '{print$1}'`
#        echo "${App_Type}构建生成的包完整路径为: $Target_JAR_Path"
#        echo "${App_Type}构建生成的包为:$JAR_WAR_NAME "
#        echo "${App_Type}构建生成的包大小为:$JAR_WAR_SIZE "
#        echo "开始删除本次构建生成的临时文件"
        Get_File_Name_Size
        rm -rf $File_TMP_JAR && [ $? -eq 0 ]  && echo "临时文件$File_TMP_JAR删除成功"
       fi
}
# 构建镜像文件
function Build_Images() {
     if [[ "${App_Type}" == "Tomcat" ]] ; then
         Image_Base_Dir=/usr/local/jenkins/build_file_ccim
         cd $Image_Base_Dir

     elif [[ "${App_Type}" == "Static" && "${JOB_NAME}" == "Docker-rms-front-demo" ]] ; then
             Image_Base_Dir=/usr/local/jenkins/build_rms_front
             cd $Image_Base_Dir
              Image_Tag=`date +%F`
              Build_Image_Push=10.215.50.190/rms_images/${BUILD_ENV}-nginx:v5
              echo "#################$Build_Image_Push $Image_Base_Dir"
              echo "开始构建镜像文件"
              docker build . -t $Build_Image_Push
              [ $? -eq 0 ] && echo "镜像构建成功"
              echo "开始上传镜像文件"
              docker push $Build_Image_Push
        [ $? -eq 0 ] && echo "镜像上传成功"
     else

        Image_Base_Dir=/usr/local/jenkins/build_file_rms
        cd $Image_Base_Dir
        Image_Tag=`date +%F`
#        Build_Image_Push=10.215.50.190/rms_images/rms/${Build_ENV}-server:${Image_Tag}
        Build_Image_Push=10.215.50.190/rms_images/rms/rms-server:v5
        echo "#################$Build_Image_Push"
        echo "开始构建镜像文件"
        docker build . -t $Build_Image_Push
        [ $? -eq 0 ] && echo "镜像构建成功"
        echo "开始上传镜像文件"
        docker push $Build_Image_Push
        [ $? -eq 0 ] && echo "镜像上传成功"
     fi
}

function Coyp_Packge() {
                Find_File_Suffix  # 调用函数
    if [[ "${App_Type}" == "Tomcat" ]] ; then
#        # 定义源路径
#        Source_Full_Path=$Target_Path$JAR_WAR_NAME
#        # 定义保存到Package目录下的包名称
#        Target_Dest_Name=`date +%F-%R`-$JAR_WAR_NAME
#        echo "Target_Dest_Name=$Target_Dest_Name"
#        echo "源路径$Source_Full_Path"
#        # 定义复制到目标目录完整路径
#        Target_Dest_Full_Path=$Pack_Base_Dir/$Target_Dest_Name
#        cp $Source_Full_Path  $Target_Dest_Full_Path
#        echo "定义复制到目标目录完整路径: $Target_Dest_Full_Path"
#        [ $? -eq 0 ] && echo "文件复制成功"
         Get_File_Absolute  # 调用函数
         # 判断软连接是否存在, 如何存在就删除
         Link_Base_Dir=/usr/local/jenkins/build_file_ccim
         # 定义软连接名称
         Dest_Link_Name=ROOT.war
         # 定义软链接完整名称用于判断软链接是否存在
         Target_Full_Link=$Link_Base_Dir/$Dest_Link_Name
#          if [  -L $Target_Full_Link ] ; then
#            echo "软链接存在，删除中$Target_Full_Link"
#            rm -rf $Target_Full_Link && [ $? -eq 0 ]  && echo "软链接删除成功$Target_Full_Link"
#            echo "创建新的软链接"
#            ln -sv $Target_Dest_Full_Path  $Link_Base_Dir/$Dest_Link_Name
#            [ $? -eq 0 ] && echo "新软连接创建成功 $Target_Full_Link"
#         else
#           ln -sv $Target_Dest_Full_Path  $Link_Base_Dir/$Dest_Link_Name
#           [ $? -eq 0 ] && echo "软连接创建成功 $Target_Full_Link"
#         fi
          \cp -f $Target_Dest_Full_Path  $Target_Full_Link
          echo "文件复制成功"
    elif [[ "${App_Type}" == "Static" &&  "${JOB_NAME}" == "Docker-rms-front-demo" ]] ; then
          echo "-----------------------------------"
          echo "$Front_Target_Full_Path"
          echo "-----------------------------------"
          \cp -f  $Front_Target_Full_Path  /usr/local/jenkins/build_rms_front/dist.zip
          [ $? -eq 0 ] && echo "前端静态文件复制完成"

    else
#        Source_Full_Path=$Target_Path$JAR_WAR_NAME
#        Target_Dest_Name=`date +%F-%R`-$JAR_WAR_NAME
#        echo "Target_Dest_Name=$Target_Dest_Name"
#        Target_Dest_Full_Path=$Pack_Base_Dir/$Target_Dest_Name
#        cp $Source_Full_Path  $Target_Dest_Full_Path
#        echo "定义复制到目标目录完整路径: $Target_Dest_Full_Path"
#        [ $? -eq 0 ] && echo "文件复制成功"
#         Get_File_Absolute
#         Link_Base_Dir=/usr/local/jenkins/build_file_ccos
#         Dest_Link_Name=call-system.jar
#         Target_Full_Link=$Link_Base_Dir/$Dest_Link_Name
         # 判断链接是否存在如果存在就删除，不存在就创建，第一次执行脚本默认是创建软连接
#         if [  -L $Target_Full_Link ] ; then
##            echo "软链接存在，删除中$Target_Full_Link"
##            rm -rf $Target_Full_Link && [ $? -eq 0 ]  && echo "软链接删除成功$Target_Full_Link"
##            echo "创建新的软链接"
##            ln -sv $Target_Dest_Full_Path  $Link_Base_Dir/$Dest_Link_Name
##            [ $? -eq 0 ] && echo "新软连接创建成功 $Target_Full_Link"
##         else
##           ln -sv $Target_Dest_Full_Path  $Link_Base_Dir/$Dest_Link_Name
##           [ $? -eq 0 ] && echo "软连接创建成功 $Target_Full_Link"
##         fi
          \cp -f /usr/local/jenkins/workspace/Docker-rms-server-demo/ymdd-rms-server/ymdd-rms-ms/target/work-hour-ms-1.0.jar      /usr/local/jenkins/build_file_rms
#          \cp -f $Target_Dest_Full_Path  $Target_Full_Link
           [ $? -eq 0 ] && echo "------------------------文件复制成功---------------------------------------------------"

    fi
}
function Remote_Call() {
    echo "创建容器Deployment"
#    Deployment_File_Name=rms-api-deployment
#    Service_File_Name=rms-api-service
    /opt/kubernetes/bin/kubectl apply -f /usr/local/jenkins/kubernetes/deployment/${Deployment_File_Name}.yaml
    [ $? -eq 0 ] && echo "配置文件加载完成"
    echo "查看Pod的deployment"
    echo "############################${Kubernetes_Deployment_Service}"
    /opt/kubernetes/bin/kubectl get pods | grep ${Kubernetes_Deployment_Service}
    echo "删除之前存在的Pod"
    Pod_Name=`/opt/kubernetes/bin/kubectl get pods | grep ${Kubernetes_Deployment_Service} | awk '{print $1}'`
    echo "将删除的Pod名称为:${Pod_Name}"
    /opt/kubernetes/bin/kubectl delete pods ${Pod_Name}
    sleep 10 && echo "创建Pod中"
     Pod_Name=`/opt/kubernetes/bin/kubectl get pods | grep ${Kubernetes_Deployment_Service} | awk '{print $1}'`
    echo "新创建的Pod名称为: ${Pod_Name}"
    echo "查看容器的日志,请等待"
    sleep 10
    /opt/kubernetes/bin/kubectl logs ${Pod_Name} | tail -3
    echo "创建Service"
    echo "${Service_File_Name}"
    /opt/kubernetes/bin/kubectl apply -f /usr/local/jenkins/kubernetes/service/${Service_File_Name}.yaml
#    echo "获取Service地址${Kubernetes_Deployment_Service}"
#    /opt/kubernetes/bin/kubectl get service |  grep ${Kubernetes_Deployment_Service}
}
Get_App_Type "${JOB_NAME}" "${App_Type}" # 调用函数
#Find_File_Suffix  # 调用函数
Coyp_Packge
Build_Images
Remote_Call

